export const CLIENTS = [
  {
    name: "Demo",
    code: "CLT-3D8D46",
    key: "demo",
    phone: "8320202940",
    email: "demo@facttwin.in",
    website: "demo.in",
    timezones: [
      {
        code: "TMZ-EB3B41",
        timezone: "Asia/Kolkata",
        country: "IST",
        offset: "+05:30",
        gmt: "19800",
        active: true,
      },
    ],
    two_factor_auth: {
      expiry: 15,
      notifications: [
        {
          key: "app",
          active: true,
          icon: "fa-regular fa-mobile-button",
          name: "App",
        },
        {
          key: "mail",
          active: true,
          icon: "fa-regular fa-envelope",
          name: "Mail",
        },
        {
          key: "web",
          active: true,
          icon: "fa-regular fa-earth-asia",
          name: "Web",
        },
      ],
      active: false,
    },
    password_policy: {
      min_pwd_length: 8,
      max_pwd_length: 24,
      lowercase: 1,
      uppercase: 1,
      numerical: 1,
      special: 1,
      pwd_history: 3,
      max_attempt: 5,
      pwd_expiry: 90,
      special_characters: "~!@#$%^&*()_+={/}|:;,<>.?",
      regex:
        "^(?=(.*[a-z]){1})(?=(.*[A-Z]){1})(?=(.*[0-9]){1})(?=(.*[~!@#$%^&*()_+={/}|:;,<>.?]){1})[a-zA-z0-9~!@#$%^&*()_+={/}|:;,<>.?]{8,24}$",
    },
    domains: {
      configuration_ui: "https://demo-config.facttwin.in",
      application_ui: "https://demo.facttwin.in",
    },
    devices: {
      web: 5,
      app: 5,
    },
    captcha: {
      attempts: 3,
      active: false,
    },
    notifications: [
      {
        key: "app",
        active: true,
        icon: "fa-regular fa-mobile-button",
        name: "App",
      },
      {
        key: "mail",
        active: true,
        icon: "fa-regular fa-envelope",
        name: "Mail",
      },
      {
        key: "web",
        active: true,
        icon: "fa-regular fa-earth-asia",
        name: "Web",
      },
    ],
    state: "draft",
    active: true,
    modules: [
      {
        key: "facttwin",
        name: "Facttwin",
        code: "FWM-82CFF0",
        order: 1,
        icon: "fa-building far",
        default: true,
        active: true,
      },
      {
        key: "smart_factory",
        name: "SmartFactory",
        code: "FWM-65FA0A",
        order: 2,
        icon: "fa-chart-line far",
        default: false,
        active: true,
      },
      {
        key: "machine_health",
        name: "Machine Health",
        code: "FWM-A9D9B3",
        order: 3,
        icon: "fa-users far",
        default: false,
        active: true,
      },
      {
        key: "energy_monitoring",
        name: "Energy Monitoring",
        code: "FWM-95E393",
        order: 4,
        icon: "fa-building far",
        default: false,
        active: true,
      },
      {
        key: "utility_monitoring",
        name: "Utility Monitoring",
        code: "FWM-EABD77",
        order: 6,
        icon: "fa-chart-line far",
        default: false,
        active: true,
      },
    ],
    carousal: [],
    created_at: "2024-08-25T08:56:38.513Z",
    updated_at: "2024-08-26T10:07:42.347Z",
    storage: {
      code: "STO-ADD6CC",
      type: "shared",
      key: "facttwin-objectstore",
      name: "facttwin",
    },
    mobile_logo: "https://sadm.facttwin.in/assets/img/facttwin.png",
    web_logo: "https://sadm.facttwin.in/assets/img/facttwin.png",
  },
  {
    name: "Amns",
    code: "CLT-BC8788",
    key: "amns",
    phone: "9261262480",
    email: "amns@facttwin.in",
    website: "amns.in",
    timezones: [
      {
        code: "TMZ-EB3B41",
        timezone: "Asia/Kolkata",
        country: "IST",
        offset: "+05:30",
        gmt: "19800",
        active: true,
      },
    ],
    two_factor_auth: {
      expiry: 15,
      notifications: [
        {
          key: "app",
          active: true,
          icon: "fa-regular fa-mobile-button",
          name: "App",
        },
        {
          key: "mail",
          active: true,
          icon: "fa-regular fa-envelope",
          name: "Mail",
        },
        {
          key: "web",
          active: true,
          icon: "fa-regular fa-earth-asia",
          name: "Web",
        },
      ],
      active: false,
    },
    password_policy: {
      min_pwd_length: 8,
      max_pwd_length: 24,
      lowercase: 1,
      uppercase: 1,
      numerical: 1,
      special: 1,
      pwd_history: 3,
      max_attempt: 5,
      pwd_expiry: 90,
      special_characters: "~!@#$%^&*()_+={/}|:;,<>.?",
      regex:
        "^(?=(.*[a-z]){1})(?=(.*[A-Z]){1})(?=(.*[0-9]){1})(?=(.*[~!@#$%^&*()_+={/}|:;,<>.?]){1})[a-zA-z0-9~!@#$%^&*()_+={/}|:;,<>.?]{8,24}$",
    },
    domains: {
      configuration_ui: "https://amns-config.facttwin.in",
      application_ui: "https://amns.facttwin.in",
    },
    devices: {
      web: 5,
      app: 5,
    },
    captcha: {
      attempts: 3,
      active: false,
    },
    notifications: [
      {
        key: "app",
        active: true,
        icon: "fa-regular fa-mobile-button",
        name: "App",
      },
      {
        key: "mail",
        active: true,
        icon: "fa-regular fa-envelope",
        name: "Mail",
      },
      {
        key: "web",
        active: true,
        icon: "fa-regular fa-earth-asia",
        name: "Web",
      },
    ],
    state: "draft",
    active: true,
    modules: [
      {
        key: "facttwin",
        name: "Facttwin",
        code: "FWM-82CFF0",
        order: 1,
        icon: "fa-building far",
        default: true,
        active: true,
      },
      {
        key: "machine_health",
        name: "Machine Health",
        code: "FWM-A9D9B3",
        order: 3,
        icon: "fa-users far",
        default: false,
        active: true,
      },
    ],
    carousal: [],
    created_at: "2024-08-25T09:02:15.407Z",
    updated_at: "2024-08-26T10:08:18.429Z",
    storage: {
      code: "STO-ADD6CC",
      type: "shared",
      key: "facttwin-objectstore",
      name: "facttwin",
    },
    mobile_logo: "https://sadm.facttwin.in/assets/img/facttwin.png",
    web_logo: "https://sadm.facttwin.in/assets/img/facttwin.png",
  },
  {
    name: "Godrej",
    code: "CLT-EF571A",
    key: "godrej",
    phone: "9569745440",
    email: "godrej@facttwin.in",
    website: "godrej.in",
    timezones: [
      {
        code: "TMZ-EB3B41",
        timezone: "Asia/Kolkata",
        country: "IST",
        offset: "+05:30",
        gmt: "19800",
        active: true,
      },
    ],
    two_factor_auth: {
      expiry: 15,
      notifications: [
        {
          key: "app",
          active: true,
          icon: "fa-regular fa-mobile-button",
          name: "App",
        },
        {
          key: "mail",
          active: true,
          icon: "fa-regular fa-envelope",
          name: "Mail",
        },
        {
          key: "web",
          active: true,
          icon: "fa-regular fa-earth-asia",
          name: "Web",
        },
      ],
      active: false,
    },
    password_policy: {
      min_pwd_length: 8,
      max_pwd_length: 24,
      lowercase: 1,
      uppercase: 1,
      numerical: 1,
      special: 1,
      pwd_history: 3,
      max_attempt: 5,
      pwd_expiry: 90,
      special_characters: "~!@#$%^&*()_+={/}|:;,<>.?",
      regex:
        "^(?=(.*[a-z]){1})(?=(.*[A-Z]){1})(?=(.*[0-9]){1})(?=(.*[~!@#$%^&*()_+={/}|:;,<>.?]){1})[a-zA-z0-9~!@#$%^&*()_+={/}|:;,<>.?]{8,24}$",
    },
    domains: {
      configuration_ui: "https://godrej-config.facttwin.in",
      application_ui: "https://godrej.facttwin.in",
    },
    devices: {
      web: 5,
      app: 5,
    },
    captcha: {
      attempts: 3,
      active: false,
    },
    notifications: [
      {
        key: "app",
        active: true,
        icon: "fa-regular fa-mobile-button",
        name: "App",
      },
      {
        key: "mail",
        active: true,
        icon: "fa-regular fa-envelope",
        name: "Mail",
      },
      {
        key: "web",
        active: true,
        icon: "fa-regular fa-earth-asia",
        name: "Web",
      },
    ],
    state: "draft",
    active: true,
    modules: [
      {
        key: "facttwin",
        name: "Facttwin",
        code: "FWM-82CFF0",
        order: 1,
        icon: "fa-building far",
        default: true,
        active: true,
      },
      {
        key: "smart_factory",
        name: "SmartFactory",
        code: "FWM-65FA0A",
        order: 2,
        icon: "fa-chart-line far",
        default: false,
        active: true,
      },
      {
        key: "machine_health",
        name: "Machine Health",
        code: "FWM-A9D9B3",
        order: 3,
        icon: "fa-users far",
        default: false,
        active: true,
      },
    ],
    carousal: [],
    created_at: "2024-08-25T09:04:29.816Z",
    updated_at: "2024-08-26T10:09:00.255Z",
    storage: {
      code: "STO-ADD6CC",
      type: "shared",
      key: "facttwin-objectstore",
      name: "facttwin",
    },
    mobile_logo: "https://sadm.facttwin.in/assets/img/facttwin.png",
    web_logo: "https://sadm.facttwin.in/assets/img/facttwin.png",
  },
  {
    name: "Spar",
    code: "CLT-7A179C",
    key: "spar",
    phone: "8439991869",
    email: "spar@facttwin.in",
    website: "spar.in",
    timezones: [
      {
        code: "TMZ-EB3B41",
        timezone: "Asia/Kolkata",
        country: "IST",
        offset: "+05:30",
        gmt: "19800",
        active: true,
      },
    ],
    two_factor_auth: {
      expiry: 15,
      notifications: [
        {
          key: "app",
          active: true,
          icon: "fa-regular fa-mobile-button",
          name: "App",
        },
        {
          key: "mail",
          active: true,
          icon: "fa-regular fa-envelope",
          name: "Mail",
        },
        {
          key: "web",
          active: true,
          icon: "fa-regular fa-earth-asia",
          name: "Web",
        },
      ],
      active: false,
    },
    password_policy: {
      min_pwd_length: 8,
      max_pwd_length: 24,
      lowercase: 1,
      uppercase: 1,
      numerical: 1,
      special: 1,
      pwd_history: 3,
      max_attempt: 5,
      pwd_expiry: 90,
      special_characters: "~!@#$%^&*()_+={/}|:;,<>.?",
      regex:
        "^(?=(.*[a-z]){1})(?=(.*[A-Z]){1})(?=(.*[0-9]){1})(?=(.*[~!@#$%^&*()_+={/}|:;,<>.?]){1})[a-zA-z0-9~!@#$%^&*()_+={/}|:;,<>.?]{8,24}$",
    },
    domains: {
      configuration_ui: "https://spar-config.facttwin.in",
      application_ui: "https://spar.facttwin.in",
    },
    devices: {
      web: 5,
      app: 5,
    },
    captcha: {
      attempts: 3,
      active: false,
    },
    notifications: [
      {
        key: "app",
        active: true,
        icon: "fa-regular fa-mobile-button",
        name: "App",
      },
      {
        key: "mail",
        active: true,
        icon: "fa-regular fa-envelope",
        name: "Mail",
      },
      {
        key: "web",
        active: true,
        icon: "fa-regular fa-earth-asia",
        name: "Web",
      },
    ],
    state: "draft",
    active: true,
    modules: [
      {
        key: "facttwin",
        name: "Facttwin",
        code: "FWM-82CFF0",
        order: 1,
        icon: "fa-building far",
        default: true,
        active: true,
      },
      {
        key: "machine_health",
        name: "Machine Health",
        code: "FWM-A9D9B3",
        order: 3,
        icon: "fa-users far",
        default: false,
        active: true,
      },
      {
        key: "utility_monitoring",
        name: "Utility Monitoring",
        code: "FWM-EABD77",
        order: 6,
        icon: "fa-chart-line far",
        default: false,
        active: true,
      },
    ],
    carousal: [],
    created_at: "2024-08-25T09:06:17.940Z",
    updated_at: "2024-08-26T10:09:43.374Z",
    storage: {
      code: "STO-ADD6CC",
      type: "shared",
      key: "facttwin-objectstore",
      name: "facttwin",
    },
    mobile_logo: "https://sadm.facttwin.in/assets/img/facttwin.png",
    web_logo: "https://sadm.facttwin.in/assets/img/facttwin.png",
  },
  {
    name: "Aachi",
    code: "CLT-BF1E21",
    key: "aachi",
    phone: "7225316116",
    email: "aachi@facttwin.in",
    website: "aachi.in",
    timezones: [
      {
        code: "TMZ-EB3B41",
        timezone: "Asia/Kolkata",
        country: "IST",
        offset: "+05:30",
        gmt: "19800",
        active: true,
      },
    ],
    two_factor_auth: {
      expiry: 15,
      notifications: [
        {
          key: "app",
          active: true,
          icon: "fa-regular fa-mobile-button",
          name: "App",
        },
        {
          key: "mail",
          active: true,
          icon: "fa-regular fa-envelope",
          name: "Mail",
        },
        {
          key: "web",
          active: true,
          icon: "fa-regular fa-earth-asia",
          name: "Web",
        },
      ],
      active: false,
    },
    password_policy: {
      min_pwd_length: 8,
      max_pwd_length: 24,
      lowercase: 1,
      uppercase: 1,
      numerical: 1,
      special: 1,
      pwd_history: 3,
      max_attempt: 5,
      pwd_expiry: 90,
      special_characters: "~!@#$%^&*()_+={/}|:;,<>.?",
      regex:
        "^(?=(.*[a-z]){1})(?=(.*[A-Z]){1})(?=(.*[0-9]){1})(?=(.*[~!@#$%^&*()_+={/}|:;,<>.?]){1})[a-zA-z0-9~!@#$%^&*()_+={/}|:;,<>.?]{8,24}$",
    },
    domains: {
      configuration_ui: "https://aachi-config.facttwin.in",
      application_ui: "https://aachi.facttwin.in",
    },
    devices: {
      web: 5,
      app: 5,
    },
    captcha: {
      attempts: 3,
      active: false,
    },
    notifications: [
      {
        key: "app",
        active: true,
        icon: "fa-regular fa-mobile-button",
        name: "App",
      },
      {
        key: "mail",
        active: true,
        icon: "fa-regular fa-envelope",
        name: "Mail",
      },
      {
        key: "web",
        active: true,
        icon: "fa-regular fa-earth-asia",
        name: "Web",
      },
    ],
    state: "draft",
    active: true,
    modules: [
      {
        key: "facttwin",
        name: "Facttwin",
        code: "FWM-82CFF0",
        order: 1,
        icon: "fa-building far",
        default: true,
        active: true,
      },
      {
        key: "smart_factory",
        name: "SmartFactory",
        code: "FWM-65FA0A",
        order: 2,
        icon: "fa-chart-line far",
        default: false,
        active: true,
      },
      {
        key: "energy_monitoring",
        name: "Energy Monitoring",
        code: "FWM-95E393",
        order: 4,
        icon: "fa-building far",
        default: false,
        active: true,
      },
    ],
    carousal: [],
    created_at: "2024-08-25T09:07:50.446Z",
    updated_at: "2024-08-26T10:04:45.910Z",
    storage: {
      code: "STO-ADD6CC",
      type: "shared",
      key: "facttwin-objectstore",
      name: "facttwin",
    },
    mobile_logo: "https://sadm.facttwin.in/assets/img/facttwin.png",
    web_logo: "https://sadm.facttwin.in/assets/img/facttwin.png",
  },
  {
    name: "Ajinomoto",
    code: "CLT-681933",
    key: "ajinomoto",
    phone: "9453326584",
    email: "ajinomoto@facttwin.in",
    website: "ajinomoto.in",
    timezones: [
      {
        code: "TMZ-EB3B41",
        timezone: "Asia/Kolkata",
        country: "IST",
        offset: "+05:30",
        gmt: "19800",
        active: true,
      },
    ],
    two_factor_auth: {
      expiry: 15,
      notifications: [
        {
          key: "app",
          active: true,
          icon: "fa-regular fa-mobile-button",
          name: "App",
        },
        {
          key: "mail",
          active: true,
          icon: "fa-regular fa-envelope",
          name: "Mail",
        },
        {
          key: "web",
          active: true,
          icon: "fa-regular fa-earth-asia",
          name: "Web",
        },
      ],
      active: false,
    },
    password_policy: {
      min_pwd_length: 8,
      max_pwd_length: 24,
      lowercase: 1,
      uppercase: 1,
      numerical: 1,
      special: 1,
      pwd_history: 3,
      max_attempt: 5,
      pwd_expiry: 90,
      special_characters: "~!@#$%^&*()_+={/}|:;,<>.?",
      regex:
        "^(?=(.*[a-z]){1})(?=(.*[A-Z]){1})(?=(.*[0-9]){1})(?=(.*[~!@#$%^&*()_+={/}|:;,<>.?]){1})[a-zA-z0-9~!@#$%^&*()_+={/}|:;,<>.?]{8,24}$",
    },
    domains: {
      configuration_ui: "https://ajinomoto-config.facttwin.in",
      application_ui: "https://ajinomoto.facttwin.in",
    },
    devices: {
      web: 5,
      app: 5,
    },
    captcha: {
      attempts: 3,
      active: false,
    },
    notifications: [
      {
        key: "app",
        active: true,
        icon: "fa-regular fa-mobile-button",
        name: "App",
      },
      {
        key: "mail",
        active: true,
        icon: "fa-regular fa-envelope",
        name: "Mail",
      },
      {
        key: "web",
        active: true,
        icon: "fa-regular fa-earth-asia",
        name: "Web",
      },
    ],
    state: "draft",
    active: true,
    modules: [
      {
        key: "facttwin",
        name: "Facttwin",
        code: "FWM-82CFF0",
        order: 1,
        icon: "fa-building far",
        default: true,
        active: true,
      },
      {
        key: "machine_health",
        name: "Machine Health",
        code: "FWM-A9D9B3",
        order: 3,
        icon: "fa-users far",
        default: false,
        active: true,
      },
    ],
    carousal: [],
    created_at: "2024-08-25T09:10:18.438Z",
    updated_at: "2024-08-26T10:10:23.045Z",
    storage: {
      code: "STO-ADD6CC",
      type: "shared",
      key: "facttwin-objectstore",
      name: "facttwin",
    },
    mobile_logo: "https://sadm.facttwin.in/assets/img/facttwin.png",
    web_logo: "https://sadm.facttwin.in/assets/img/facttwin.png",
  },
  {
    name: "Lauruslabs",
    code: "CLT-392C19",
    key: "lauruslabs",
    phone: "8281326903",
    email: "lauruslabs@facttwin.in",
    website: "lauruslabs.in",
    timezones: [
      {
        code: "TMZ-EB3B41",
        timezone: "Asia/Kolkata",
        country: "IST",
        offset: "+05:30",
        gmt: "19800",
        active: true,
      },
    ],
    two_factor_auth: {
      expiry: 15,
      notifications: [
        {
          key: "app",
          active: true,
          icon: "fa-regular fa-mobile-button",
          name: "App",
        },
        {
          key: "mail",
          active: true,
          icon: "fa-regular fa-envelope",
          name: "Mail",
        },
        {
          key: "web",
          active: true,
          icon: "fa-regular fa-earth-asia",
          name: "Web",
        },
      ],
      active: false,
    },
    password_policy: {
      min_pwd_length: 8,
      max_pwd_length: 24,
      lowercase: 1,
      uppercase: 1,
      numerical: 1,
      special: 1,
      pwd_history: 3,
      max_attempt: 5,
      pwd_expiry: 90,
      special_characters: "~!@#$%^&*()_+={/}|:;,<>.?",
      regex:
        "^(?=(.*[a-z]){1})(?=(.*[A-Z]){1})(?=(.*[0-9]){1})(?=(.*[~!@#$%^&*()_+={/}|:;,<>.?]){1})[a-zA-z0-9~!@#$%^&*()_+={/}|:;,<>.?]{8,24}$",
    },
    domains: {
      configuration_ui: "https://lauruslabs-config.facttwin.in",
      application_ui: "https://lauruslabs.facttwin.in",
    },
    devices: {
      web: 5,
      app: 5,
    },
    captcha: {
      attempts: 3,
      active: false,
    },
    notifications: [
      {
        key: "app",
        active: true,
        icon: "fa-regular fa-mobile-button",
        name: "App",
      },
      {
        key: "mail",
        active: true,
        icon: "fa-regular fa-envelope",
        name: "Mail",
      },
      {
        key: "web",
        active: true,
        icon: "fa-regular fa-earth-asia",
        name: "Web",
      },
    ],
    state: "draft",
    active: true,
    modules: [
      {
        key: "facttwin",
        name: "Facttwin",
        code: "FWM-82CFF0",
        order: 1,
        icon: "fa-building far",
        default: true,
        active: true,
      },
      {
        key: "smart_factory",
        name: "SmartFactory",
        code: "FWM-65FA0A",
        order: 2,
        icon: "fa-chart-line far",
        default: false,
        active: true,
      },
      {
        key: "machine_health",
        name: "Machine Health",
        code: "FWM-A9D9B3",
        order: 3,
        icon: "fa-users far",
        default: false,
        active: true,
      },
    ],
    carousal: [],
    created_at: "2024-08-25T09:12:24.511Z",
    updated_at: "2024-08-26T10:06:08.452Z",
    storage: {
      code: "STO-ADD6CC",
      type: "shared",
      key: "facttwin-objectstore",
      name: "facttwin",
    },
    mobile_logo: "https://sadm.facttwin.in/assets/img/facttwin.png",
    web_logo: "https://sadm.facttwin.in/assets/img/facttwin.png",
  },
  {
    name: "Uniparts",
    code: "CLT-BCE3B2",
    key: "uniparts",
    phone: "9053433162",
    email: "uniparts@facttwin.in",
    website: "uniparts.in",
    timezones: [
      {
        code: "TMZ-EB3B41",
        timezone: "Asia/Kolkata",
        country: "IST",
        offset: "+05:30",
        gmt: "19800",
        active: true,
      },
    ],
    two_factor_auth: {
      expiry: 15,
      notifications: [
        {
          key: "app",
          active: true,
          icon: "fa-regular fa-mobile-button",
          name: "App",
        },
        {
          key: "mail",
          active: true,
          icon: "fa-regular fa-envelope",
          name: "Mail",
        },
        {
          key: "web",
          active: true,
          icon: "fa-regular fa-earth-asia",
          name: "Web",
        },
      ],
      active: false,
    },
    password_policy: {
      min_pwd_length: 8,
      max_pwd_length: 24,
      lowercase: 1,
      uppercase: 1,
      numerical: 1,
      special: 1,
      pwd_history: 3,
      max_attempt: 5,
      pwd_expiry: 90,
      special_characters: "~!@#$%^&*()_+={/}|:;,<>.?",
      regex:
        "^(?=(.*[a-z]){1})(?=(.*[A-Z]){1})(?=(.*[0-9]){1})(?=(.*[~!@#$%^&*()_+={/}|:;,<>.?]){1})[a-zA-z0-9~!@#$%^&*()_+={/}|:;,<>.?]{8,24}$",
    },
    domains: {
      configuration_ui: "https://uniparts-config.facttwin.in",
      application_ui: "https://uniparts.facttwin.in",
    },
    devices: {
      web: 5,
      app: 5,
    },
    captcha: {
      attempts: 3,
      active: false,
    },
    notifications: [
      {
        key: "app",
        active: true,
        icon: "fa-regular fa-mobile-button",
        name: "App",
      },
      {
        key: "mail",
        active: true,
        icon: "fa-regular fa-envelope",
        name: "Mail",
      },
      {
        key: "web",
        active: true,
        icon: "fa-regular fa-earth-asia",
        name: "Web",
      },
    ],
    state: "draft",
    active: true,
    modules: [
      {
        key: "facttwin",
        name: "Facttwin",
        code: "FWM-82CFF0",
        order: 1,
        icon: "fa-building far",
        default: true,
        active: true,
      },
      {
        key: "machine_health",
        name: "Machine Health",
        code: "FWM-A9D9B3",
        order: 3,
        icon: "fa-users far",
        default: false,
        active: true,
      },
    ],
    carousal: [],
    created_at: "2024-08-25T09:14:02.637Z",
    updated_at: "2024-08-28T08:34:06.552Z",
    mobile_logo: "https://sadm.facttwin.in/assets/img/facttwin.png",
    web_logo: "https://sadm.facttwin.in/assets/img/facttwin.png",
    storage: {
      code: "STO-ADD6CC",
      type: "shared",
      key: "facttwin-objectstore",
      name: "facttwin",
    },
  },
  {
    name: "FMCG",
    code: "CLT-97D740",
    key: "fmcg",
    phone: "9848099884",
    email: "fmcg@facttwin.in",
    website: "fmcg.in",
    timezones: [
      {
        code: "TMZ-EB3B41",
        timezone: "Asia/Kolkata",
        country: "IST",
        offset: "+05:30",
        gmt: "19800",
        active: true,
      },
    ],
    two_factor_auth: {
      expiry: 15,
      notifications: [
        {
          key: "app",
          active: true,
          icon: "fa-regular fa-mobile-button",
          name: "App",
        },
        {
          key: "mail",
          active: true,
          icon: "fa-regular fa-envelope",
          name: "Mail",
        },
        {
          key: "web",
          active: true,
          icon: "fa-regular fa-earth-asia",
          name: "Web",
        },
      ],
      active: false,
    },
    password_policy: {
      min_pwd_length: 8,
      max_pwd_length: 24,
      lowercase: 1,
      uppercase: 1,
      numerical: 1,
      special: 1,
      pwd_history: 3,
      max_attempt: 5,
      pwd_expiry: 90,
      special_characters: "~!@#$%^&*()_+={/}|:;,<>.?",
      regex:
        "^(?=(.*[a-z]){1})(?=(.*[A-Z]){1})(?=(.*[0-9]){1})(?=(.*[~!@#$%^&*()_+={/}|:;,<>.?]){1})[a-zA-z0-9~!@#$%^&*()_+={/}|:;,<>.?]{8,24}$",
    },
    domains: {
      configuration_ui: "https://fmcg-config.facttwin.in",
      application_ui: "https://fmcg.facttwin.in",
    },
    devices: {
      web: 5,
      app: 5,
    },
    captcha: {
      attempts: 3,
      active: false,
    },
    notifications: [
      {
        key: "app",
        active: true,
        icon: "fa-regular fa-mobile-button",
        name: "App",
      },
      {
        key: "mail",
        active: true,
        icon: "fa-regular fa-envelope",
        name: "Mail",
      },
      {
        key: "web",
        active: true,
        icon: "fa-regular fa-earth-asia",
        name: "Web",
      },
    ],
    state: "draft",
    active: true,
    modules: [
      {
        key: "facttwin",
        name: "Facttwin",
        code: "FWM-82CFF0",
        order: 1,
        icon: "fa-building far",
        default: true,
        active: true,
      },
      {
        key: "smart_factory",
        name: "SmartFactory",
        code: "FWM-65FA0A",
        order: 2,
        icon: "fa-chart-line far",
        default: false,
        active: true,
      },
    ],
    carousal: [],
    created_at: "2024-08-25T09:16:03.525Z",
    updated_at: "2024-08-28T12:05:02.523Z",
    storage: {
      code: "STO-ADD6CC",
      type: "shared",
      key: "facttwin-objectstore",
      name: "facttwin",
    },
    mobile_logo: "https://sadm.facttwin.in/assets/img/facttwin.png",
    web_logo: "https://sadm.facttwin.in/assets/img/facttwin.png",
  },
];
